spring.application.name=ecommerce
//spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
//spring.datasource.username=root
//spring.datasource.password=Nigam@315
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8089
jwt.secret=5ba1d97618d04e3bbff6787108965ebc17337377ec1a4590888e244d0ca4a3f3
jwt.expiration=86400000
cloudinary.cloud-name = dvv08vwk2
cloudinary.api-key = 817452612274464
cloudinary.api-secret = kmmbGmf6bdeH0aXBVXlNguB8Ng0
razorpay.key.id = rzp_test_SLGlPsakU2aaVK
razorpay.key.secret = P7X9ChENGrx3g7V4qnTTNnOU
spring.datasource.url = jdbc:mysql://root:rvVdNxMSRFdfdqmAeTEjpzsIarfArErQ@shuttle.proxy.rlwy.net:36717/railway
spring.datasource.username=root
spring.datasource.password=rvVdNxMSRFdfdqmAeTEjpzsIarfArErQ

app.dev-mode = true
