spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Nigam@315
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8089
jwt.secret=mySuperSecretJwtKey123456789012345
jwt.expiration=86400000
cloudinary.cloud-name = dvv08vwk2
cloudinary.api-key = 182577893382354
cloudinary.api-secret = d7ZVLDxbJHRfj3xFp8_TIZ826dA
razorpay.key.id = rzp_test_SBJ9Q8O9m1Pv8A
razorpay.key.secret = rLst7k8QPWf85JfnVhlXT0PR


app.dev-mode = true
